language: node_js

node_js:
  - 0.10

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

addons:
  sauce_connect: true

env:
  matrix:
    - BROWSER_NAME='firefox' BROWSER_VERSION='40' PLATFORM='Windows 7'
    - BROWSER_NAME='firefox' BROWSER_VERSION='40' PLATFORM='OSX 10.9'
    - BROWSER_NAME='chrome' BROWSER_VERSION='43' PLATFORM='Windows 7'
    - BROWSER_NAME='chrome' BROWSER_VERSION='43' PLATFORM='OSX 10.9'
    - BROWSER_NAME='chrome' BROWSER_VERSION='44' PLATFORM='Windows 7'
    - BROWSER_NAME='chrome' BROWSER_VERSION='44' PLATFORM='OSX 10.9'
    - BROWSER_NAME='chrome' BROWSER_VERSION='45' PLATFORM='OSX 10.9'
    - BROWSER_NAME='chrome' BROWSER_VERSION='46' PLATFORM='OSX 10.9'
  global:
    - secure: OaF1EHbUU+0vO3zdO70VlLVOuojRMnWhF02Lj3S7sP4+lbM3CY3JmEyB8G18G3x2aVyqgBEWLkh5WXahNuQIwnTYfidpbeJhvZD4xcP4zxgVyV6DLbxVN+lUpY2maOgCyDPGAix08HMWwuJss2Cw83bdmm0cJv/r2x6YXa/FpUA=
    - secure: AdCl4LiKCMEOBAdltT/aAQVSmqnPZfCc/z2z7VPKCR/s1LbiD1i3ADJin5SgsglhWnmJToam5msNXEvL4gaT0dtlxtiw8ygutzQwEewPSLyekXuAF2NCt+63IdWWt6z470Cb6Nojrz0hRkiKzzeEjF2j1GFmrWkYzgYahlvi4sE=

before_script:
  - npm install -g bower
  - bower install
script: TEST_SERVER_PORT=8090 npm test
